// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Database;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhomHangEntity", b =>
                {
                    b.Property<int>("NhomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhomId"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NhomHangEntityNhomId")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NhomId");

                    b.HasIndex("NhomHangEntityNhomId");

                    b.ToTable("NhomHang");
                });

            modelBuilder.Entity("WebApplication1.Database.Entities.HangHoaEntity", b =>
                {
                    b.Property<int>("HangHoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HangHoaId"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("NhomHangId")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHoa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("HangHoaId");

                    b.HasIndex("NhomHangId");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("NhomHangEntity", b =>
                {
                    b.HasOne("NhomHangEntity", null)
                        .WithMany("HangHoas")
                        .HasForeignKey("NhomHangEntityNhomId");
                });

            modelBuilder.Entity("WebApplication1.Database.Entities.HangHoaEntity", b =>
                {
                    b.HasOne("NhomHangEntity", "NhomHang")
                        .WithMany()
                        .HasForeignKey("NhomHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomHang");
                });

            modelBuilder.Entity("NhomHangEntity", b =>
                {
                    b.Navigation("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
